---
abstract: 'Allow Tests to output Boost C++ XML format test reports'
author:
  - 'q{Robert Haxton <robert.haxton@gmail.com>}'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-BoostUnit
provides:
  Test::BoostUnit:
    file: lib/Test/BoostUnit.pm
    version: 0.05
requires:
  Digest::MD5: 0
  File::Find: 0
  Getopt::CommandLineExports: 0
  List::Util: 0
  Test::More: 0
version: 0.05
